name: project
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - anaconda
  - pip=20.2.4
  - pytorch-lightning=1.1.2
  - pytorch=1.7.1
  - pip:
      - -e .
      - -r file:requirements.txt
      - -r file:tests/requirements.txt
